import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'

import { ENTRANCE } from '../config'
import './globals.css'

/*
 * Arm the entrance before the first paint.
 *
 * Without this the server's settled page paints, hydration runs, and only then
 * does the entrance take over — a visible flash of the masthead, which would
 * be in every screen recording. Eleven lines inline is the price of not having
 * that. It writes one attribute and nothing else; the instrument removes it,
 * and removes it anyway if the field never comes up.
 */
const ARM = `(function(){try{
var p=new URLSearchParams(location.search);
var forced=p.get('entrance')==='1';
var reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(forced||!reduced)document.documentElement.setAttribute('data-entrance','arming');
}catch(e){}})()`

const TITLE = 'The Thirty-First Day'
const DESCRIPTION =
  'An independent study of what happens to The Standard Reserve when its first wave of dormant genesis bankers is revoked.'

const SITE_URL = process.env['NEXT_PUBLIC_SITE_URL'] ?? 'https://day31.xyz'

/**
 * The social card is a committed file, `public/og.png`, regenerated by
 * `pnpm og`. Not Next's metadata-image route: that exports without a file
 * extension, and the host then serves it as `application/octet-stream`, which
 * scrapers decline to render as a card. That was checked on a real deploy, not
 * assumed.
 */
const OG_ALT =
  'The Thirty-First Day — on day 31 the issuance multiplier delta is exactly 0.0000, in all 200 seeds.'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: TITLE,
  authors: [{ name: 'Independent' }],
  alternates: { canonical: '/' },
  openGraph: {
    type: 'article',
    title: TITLE,
    description: DESCRIPTION,
    siteName: TITLE,
    url: SITE_URL,
    images: [{ url: '/og.png', width: 1200, height: 630, alt: OG_ALT }],
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    images: [{ url: '/og.png', alt: OG_ALT }],
  },
  robots: { index: true, follow: true },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#eeebe5' },
    { media: '(prefers-color-scheme: dark)', color: '#100d09' },
  ],
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {ENTRANCE ? <script dangerouslySetInnerHTML={{ __html: ARM }} /> : null}
        {children}
      </body>
    </html>
  )
}
