import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'

import './globals.css'

const TITLE = 'The Thirty-First Day'
const DESCRIPTION =
  'An independent study of what happens to The Standard Reserve when its first wave of dormant genesis bankers is revoked.'

const SITE_URL = process.env['NEXT_PUBLIC_SITE_URL'] ?? 'https://thirty-first-day.vercel.app'

/**
 * The social card is a committed file, `public/og.png`, regenerated by
 * `pnpm og`. Not Next's metadata-image route: that exports without a file
 * extension, and the host then serves it as `application/octet-stream`, which
 * scrapers decline to render as a card. That was checked on a real deploy, not
 * assumed.
 */
const OG_ALT =
  'The Thirty-First Day — on day 31 the issuance multiplier delta is exactly 0.0000, in all 200 seeds.'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: TITLE,
  authors: [{ name: 'Independent' }],
  openGraph: {
    type: 'article',
    title: TITLE,
    description: DESCRIPTION,
    siteName: TITLE,
    url: SITE_URL,
    images: [{ url: '/og.png', width: 1200, height: 630, alt: OG_ALT }],
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    images: [{ url: '/og.png', alt: OG_ALT }],
  },
  robots: { index: true, follow: true },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#faf9f7' },
    { media: '(prefers-color-scheme: dark)', color: '#121210' },
  ],
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
